# Numpy is core library for Numerical computing 

Its consist of multi-dimensional array object and you will process it 

In [1]:
import numpy as np

In [2]:
n1=np.array([1,2,3,4,])
n1

array([1, 2, 3, 4])

In [7]:
# multi-dimension

In [3]:
n2= np.array([[1,2,3],[4,5,6]])

In [4]:
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(n2)

numpy.ndarray

In [6]:
# Initializing numpy array with zeros 

In [8]:
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [9]:
n1=np.full((2,3),12)
n1

array([[12, 12, 12],
       [12, 12, 12]])

In [10]:
# Initializing numpy with arange 

In [11]:
n1=np.arange(10,20)           # start , end-exclusive

In [12]:
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
n2= np.arange(10,50,5)    # start, end -exclusive , stepping

In [16]:
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
# Initailizing numpy with random number 

In [18]:
n3=np.random.randint(1,100,5)   # Any 5 random numbers B/w 1 to 100

In [19]:
n3

array([53, 31, 51, 82, 48])

In [20]:
# Shape method-  consist the row and column of your array

In [27]:
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

In [28]:
# how to change of your array shape 

In [29]:
n1.shape=(3,2)
n1.shape

(3, 2)

In [30]:
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

# joining Numpy arrays

In [34]:
# vstack() vertical stack 
# hstack() horizontal stack
# column_stack()

In [33]:
n4=np.array([10,20,30,])
n5=np.array([40,50,60])
np.vstack((n4,n5))

array([[10, 20, 30],
       [40, 50, 60]])

In [35]:
np.hstack((n4,n5))

array([10, 20, 30, 40, 50, 60])

In [36]:
np.column_stack((n4,n5))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [37]:
# Intersection (common elements)

In [42]:
n1=np.array([1,2,3,4,5,6])
n2=np.array([5,6,7,8,9])
np.intersect1d(n1,n2)

array([5, 6])

In [43]:
np.setdiff1d(n1,n2)     # n1-n2

array([1, 2, 3, 4])

In [44]:
np.setdiff1d(n2,n1)   # common element eliminate 

array([7, 8, 9])

In [45]:
# Addition of numpy array 

In [46]:
m1=np.array([10,20])
m2= np.array([30,40])
np.sum([m1,m2])

100

In [47]:
np.sum([m1,m2],axis=0)     # columns add

array([40, 60])

In [48]:
np.sum([m1,m2],axis=1)    # rows add

array([30, 70])

In [49]:
# Numpy Array with Mathematics 

In [50]:
# Basic add
n1=np.array([10,20,30])

In [51]:
n1=n1+1

In [52]:
n1

array([11, 21, 31])

In [55]:
n1=np.array([10,20,30])
n1=n1*2
n1

array([20, 40, 60])

In [56]:
n1=np.array([10,20,30])
n1=n1-1
n1

array([ 9, 19, 29])

In [57]:
n1=np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

Numpy Math Function

In [58]:
# mean
n1=np.array([10,45,8,50,18,60])
np.mean(n1)

31.833333333333332

In [60]:
n2=np.random.randint(11,40,6)
n2

array([34, 17, 22, 15, 35, 24])

In [61]:
np.median(n2)

23.0

In [62]:
np.std(n2)

7.675719293112969